export const queryKeys = {
  dashboard: ['dashboard'] as const,
  routines: ['routines'] as const,
  activeWorkout: ['activeWorkout'] as const,
  workout: (id: string) => ['workout', id] as const,
  recentWorkouts: ['recentWorkouts'] as const,
  workoutPlans: (start: string, end: string) => ['workoutPlans', start, end] as const,
  workoutSessions: ['workoutSessions'] as const,
  workoutSessionsForRange: (start: string, end: string) => ['workoutSessions', start, end] as const,
  diary: (date: string) => ['diary', date] as const,
  foodSearch: (query: string) => ['foodSearch', query] as const,
  recentFoods: ['recentFoods'] as const,
  profile: ['profile'] as const,
  progress: ['progress'] as const,
  progressOverview: (range: string) => ['progressOverview', range] as const,
  progressOverviewModules: ['progressOverviewModules'] as const,
  progressWidgets: ['progressWidgets'] as const,
  progressWidget: (id: string) => ['progressWidget', id] as const,
  progressWidgetData: (id: string, updatedAt: string) => ['progressWidgetData', id, updatedAt] as const,
  exercises: ['exercises'] as const,
  exerciseHistory: (id: string) => ['exerciseHistory', id] as const,
};
