type FoodSearchItemTypeKey = 'food' | 'drink' | 'all';

export const queryKeys = {
  dashboard: ['dashboard'] as const,
  routines: ['routines'] as const,
  activeWorkout: ['activeWorkout'] as const,
  workout: (id: string) => ['workout', id] as const,
  recentWorkouts: ['recentWorkouts'] as const,
  completedWorkoutCount: ['completedWorkoutCount'] as const,
  workoutPlans: (start: string, end: string) => ['workoutPlans', start, end] as const,
  programSchedule: (start: string, end: string) => ['programSchedule', start, end] as const,
  programDayOutcomes: (start: string, end: string) => ['programDayOutcomes', start, end] as const,
  workoutSessions: ['workoutSessions'] as const,
  workoutSessionsForRange: (start: string, end: string) => ['workoutSessions', start, end] as const,
  diary: (date: string) => ['diary', date] as const,
  weeklyCalories: (endDate: string) => ['weeklyCalories', endDate] as const,
  calorieStreak: (endDate: string) => ['calorieStreak', endDate] as const,
  caffeineToday: (localDate: string) => ['caffeineToday', localDate] as const,
  foodSearch: (query: string, itemType: FoodSearchItemTypeKey = 'food') => ['foodSearch', itemType, query] as const,
  recentFoods: (itemType: FoodSearchItemTypeKey = 'food') => ['recentFoods', itemType] as const,
  frequentlyLoggedFoods: (itemType: FoodSearchItemTypeKey = 'food') => ['frequentlyLoggedFoods', itemType] as const,
  nutritionLibrary: ['nutritionLibrary'] as const,
  mealsPerDayTarget: ['mealsPerDayTarget'] as const,
  profile: ['profile'] as const,
  progress: ['progress'] as const,
  progressOverview: (range: string) => ['progressOverview', range] as const,
  progressOverviewModules: ['progressOverviewModules'] as const,
  progressWidgets: ['progressWidgets'] as const,
  progressWidget: (id: string) => ['progressWidget', id] as const,
  progressWidgetData: (id: string, updatedAt: string) => ['progressWidgetData', id, updatedAt] as const,
  exercises: ['exercises'] as const,
  exerciseSearch: (query = '', primaryMuscle = 'All', equipment = 'All', category = 'All') =>
    ['exerciseSearch', query, primaryMuscle, equipment, category] as const,
  exerciseFilterOptions: ['exerciseFilterOptions'] as const,
  exerciseHistory: (id: string) => ['exerciseHistory', id] as const,
};
